# Generated by Django 5.2.5 on 2025-09-30 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regles_Filter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chaine', models.CharField(max_length=255)),
                ('protocol', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP'), ('icmp', 'ICMP'), ('all', 'ALL')], default='all', max_length=10)),
                ('port_source', models.IntegerField(blank=True, null=True)),
                ('port_destination', models.IntegerField(blank=True, null=True)),
                ('interface_dentree', models.CharField(blank=True, max_length=100, null=True)),
                ('interface_sortie', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_source', models.GenericIPAddressField(blank=True, null=True)),
                ('ip_destination', models.GenericIPAddressField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('ACCEPT', 'Accept'), ('DROP', 'Drop'), ('REJECT', 'Reject'), ('LOG', 'Log')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Regles_Mangle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chaine', models.CharField(max_length=255)),
                ('protocol', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP'), ('icmp', 'ICMP'), ('all', 'ALL')], default='all', max_length=10)),
                ('port_source', models.IntegerField(blank=True, null=True)),
                ('port_destination', models.IntegerField(blank=True, null=True)),
                ('interface_dentree', models.CharField(blank=True, max_length=100, null=True)),
                ('interface_sortie', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_source', models.GenericIPAddressField(blank=True, null=True)),
                ('ip_destination', models.GenericIPAddressField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('ttl_value', models.IntegerField(blank=True, help_text='Nouvelle valeur du TTL', null=True)),
                ('tos_value', models.CharField(blank=True, help_text='Valeur TOS ou DSCP', max_length=50, null=True)),
                ('mark_value', models.IntegerField(blank=True, help_text='Marque appliquée au paquet', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Regles_NAT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chaine', models.CharField(max_length=255)),
                ('protocol', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP'), ('icmp', 'ICMP'), ('all', 'ALL')], default='all', max_length=10)),
                ('port_source', models.IntegerField(blank=True, null=True)),
                ('port_destination', models.IntegerField(blank=True, null=True)),
                ('interface_dentree', models.CharField(blank=True, max_length=100, null=True)),
                ('interface_sortie', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_source', models.GenericIPAddressField(blank=True, null=True)),
                ('ip_destination', models.GenericIPAddressField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('SNAT', 'Source NAT'), ('DNAT', 'Destination NAT'), ('MASQUERADE', 'Masquerade')], max_length=15)),
                ('new_ip_source', models.GenericIPAddressField(blank=True, null=True)),
                ('new_ip_destination', models.GenericIPAddressField(blank=True, null=True)),
                ('new_port', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description_suggestion', models.TextField()),
                ('date_declenchement', models.DateTimeField(auto_now_add=True)),
                ('chaine', models.CharField(default='INPUT', max_length=255)),
                ('protocol', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP'), ('icmp', 'ICMP'), ('all', 'ALL')], default='all', max_length=10)),
                ('port_source', models.IntegerField(blank=True, null=True)),
                ('port_destination', models.IntegerField(blank=True, null=True)),
                ('interface_dentree', models.CharField(blank=True, max_length=100, null=True)),
                ('interface_sortie', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_source', models.GenericIPAddressField(blank=True, null=True)),
                ('ip_destination', models.GenericIPAddressField(blank=True, null=True)),
                ('action', models.CharField(choices=[('ACCEPT', 'Accept'), ('DROP', 'Drop'), ('REJECT', 'Reject'), ('LOG', 'Log')], default='ACCEPT', max_length=10)),
                ('statut', models.CharField(choices=[('proposee', 'Proposée'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='proposee', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('superadmin', 'Super Administrateur'), ('admin', 'Administrateur')], default='admin', max_length=20)),
            ],
        ),
    ]
